apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "workshop-cloud-kube"
  namespace: "default"
  labels:
    app: "workshop-cloud-kube"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: "workshop-cloud-kube"
  template:
    metadata:
      labels:
        app: "workshop-cloud-kube"
    spec:
      containers:
        - name: "workshop-cloud-sha256-1"
          image: "southamerica-east1-docker.pkg.dev/workshop-cloud-340123/workshop-cloud/front:latest"
          resources:
            #cpu and memory limit
            limits:
              memory: "550Mi"
              cpu: "500m"
          ports:
            #the port on which the app can be reached out inside the container
            - containerPort: 80
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "workshop-cloud-kube-hpa-hfiz"
  namespace: "default"
  labels:
    app: "workshop-cloud-kube"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "workshop-cloud-kube"
    apiVersion: "apps/v1"
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
